"use client";

import Link from 'next/link';
import { Sparkles } from 'lucide-react';

export function Hero() {
  return (
    <section className="min-h-screen flex items-center bg-gradient-to-b from-green-50 to-white">
      <div className="container mx-auto px-4 relative">
        <div className="flex flex-col items-center justify-center text-center mb-16">
          <h1 className="text-4xl md:text-5xl font-bold text-gray-900 mb-4">
            Transform Your Agricultural Practice
          </h1>
          <h2 className="text-xl md:text-2xl text-gray-600 mb-8">
            Crop rotation, soil and harvest tracking, financial reporting, and AI assistants for every stage of the season
          </h2>
          <div className="flex flex-wrap items-center justify-center gap-4">
            <Link
              href="/dashboard"
              className="inline-flex items-center px-6 py-3 border border-transparent text-base font-medium rounded-md text-white bg-green-600 hover:bg-green-700 transition-colors"
            >
              Access Dashboard
            </Link>
            <Link
              href="/Premium"
              className="inline-flex items-center gap-1.5 px-6 py-3 border border-amber-400 text-base font-medium rounded-md text-amber-800 bg-amber-50 hover:bg-amber-100 transition-colors"
            >
              <Sparkles className="w-4 h-4" /> See Premium Plans
            </Link>
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
          <div className="bg-white p-6 rounded-xl shadow-sm hover:shadow-md transition-shadow">
            <div className="text-green-600 text-3xl mb-4">🌱</div>
            <h4 className="text-xl font-semibold text-gray-900 mb-2">
              <Link href="/Rotatie" className="hover:text-green-600 transition-colors">
                Crop Rotation
              </Link>
            </h4>
            <p className="text-gray-600">
              Plan rotations and get an AI rotation health advisor that flags risks before you plant
            </p>
          </div>

          <div className="bg-white p-6 rounded-xl shadow-sm hover:shadow-md transition-shadow">
            <div className="text-green-600 text-3xl mb-4">🔍</div>
            <h4 className="text-xl font-semibold text-gray-900 mb-2">
              <Link href="/CropWiki" className="hover:text-green-600 transition-colors">
                AI Crop Encyclopedia
              </Link>
            </h4>
            <p className="text-gray-600">
              Look up any crop&apos;s soil, climate, and fertilizer needs, generated by AI when it&apos;s not already in our database
            </p>
          </div>

          <div className="bg-white p-6 rounded-xl shadow-sm hover:shadow-md transition-shadow">
            <div className="text-green-600 text-3xl mb-4">🐛</div>
            <h4 className="text-xl font-semibold text-gray-900 mb-2">
              <Link href="/PestDiagnosis" className="hover:text-green-600 transition-colors">
                Pest & Disease Diagnosis
              </Link>
            </h4>
            <p className="text-gray-600">
              Describe what you&apos;re seeing on your crop and get AI-assisted suggestions on likely causes
            </p>
          </div>

          <div className="bg-white p-6 rounded-xl shadow-sm hover:shadow-md transition-shadow">
            <div className="text-green-600 text-3xl mb-4">📊</div>
            <h4 className="text-xl font-semibold text-gray-900 mb-2">
              <Link href="/dashboard" className="hover:text-green-600 transition-colors">
                Harvest, Finance & Analytics
              </Link>
            </h4>
            <p className="text-gray-600">
              Track yields and costs, see profit and loss, and get a live picture of your farm&apos;s performance
            </p>
          </div>
        </div>
      </div>
    </section>
  );
}
